#+TITLE: Jegyzet a Cisco IOS oprendszerhez

* Általános IOS ismeretek

** Konfigurációs szintek

   - *User EXEC mode* (=>=): csak alapvető parancsok adhatóak ki,
     pl. státusz 

   - *Privileged EXEC mode* (=#=): User EXEC mode-ból az ~enable~
     paranccsal érhető el. Innen érhetőek el a konfigurációs módok,
     illetve itt lehet perzisztensé tenni a futó konfigurációt

   - *Global Configuration mode* (=(config)=): Privileged EXEC mode-ból
     a ~configure terminal~ paranccsal érhető el. Innen érhető el a
     többi alkonfigurációs szint, pl.: interface (=(config-if)=), line
     (=(config-li)=), router
     
   - Az alacsonyabb szintekre mindig az ~exit~ paranccsal lehet visszatérni

** Segítség

   - A =?= megadja az összes lehetséges parancs vagy argumentum
     értékét. Megkezdett parancsoknál és argumentumoknál is
     használható

   - A =<TAB>= gomb kiegészíti a parancsot vagy argumentumot a teljes
     nevére

   - Nem muszáj minden parancs vagy argumentum nevét teljesen kiírni,
     viszont a leírt rövidítéseknek egyértelműen kell azonosítaniuk a
     parancsot vagy az argumentumot

** Korábbi parancsok
   - fölfelé nyíl vagy C-p: előző parancs
   - lefelé nyíl vagy C-n: következő parancs
   - alapból a legutóbbi 10 parancs van eltárolva
   - ~show history~ paranccsal előhozhatóak Privileged EXEC mode-ban
   - ~terminal history size <szám>~ paranccsal bővíthető

* Globális konfiguráció

** Hosztnév beállítás
Global config mode-ban kell kiadni
#+BEGIN_SRC sh
hostname <hosztnév>
#+END_SRC

** Banner üzenet beállítása, ami megjelenik minden belépés előtt
Global config mode-ban kell kiadni 
#+BEGIN_SRC sh
banner motd <tetszőleges elválasztójel> <Üzenet, amiben figyelmeztetjük az
illetéktelen behatolókat, hogy törvénysértést követnek el>
<ugyanaz a tetszőleges elválasztójel>
#+END_SRC

** Default gateway beállítás
Global config mode-ban kell kiadni
#+BEGIN_SRC sh
ip default-gateway <ip-cím>
#+END_SRC

** Jelenleg futó konfiguráció elmentése
Privileged EXEC mode-ban kell kiadni.
#+BEGIN_SRC sh
copy running_config startup_config
#+END_SRC

** DNS lookup letiltása
Privileged EXEC mode-ban kell kiadni
#+BEGIN_SRC sh
no ip domain lookup
#+END_SRC

** BOOT környezeti változó beállítása
A BOOT környezeti változó beállításával adható meg a boot loader
számára, hogy hol keresse meg az IOS-t a flash tárolón
#+BEGIN_SRC sh
boot system flash:<IOS bináris>
#+END_SRC

* Interfészek konfigurálása

** Konzol jelszó beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
line console 0
password <jelszó>
login
#+END_SRC

** Virtuális terminál jelszó beállítás
Global config mode-ban kell lenni. A virtuális terminálok száma 0-tól
15-ig tart
#+BEGIN_SRC sh
line vty 0 15
passwod <jelszó>
login
#+END_SRC

** Interfész ip beállítás
Global config mode-ban kell lenni. A switchen =vlan 1=, a routeteren
=gigabithethernet= vagy =fastethernet= vagy valami ilyesmi a nevük
#+BEGIN_SRC sh
interface <interfésznév>
ip address <ip cím> <subnet mask pontozott decimális formában>
[description <rövid leírás interfészről>]
no shutdown
#+END_SRC

** Interfész ipv6 beállítás
Global config mode-ban kell lenni. A switchen =vlan 1=, a routeteren
=gigabithethernet= vagy =fastethernet= vagy valami ilyesmi a nevük
#+BEGIN_SRC sh
interface <interfésznév>
ipv6 address <global ipv6-cím>/<prefix-hossz decimálisan> [eui-64]
ipv6 address <link-local unicast ipv6-cím>/<prefix-hossz decimálisan> link-local
[description <rövid leírás interfészről>]
no shutdown
#+END_SRC
Ezek után ki kell adni =Global config mode=-ban az ~Ipv6
unicast-routing~ parancsot az unicast csomagok továbbításához

** Interfész loopback beállítás
Global config mode-ban kell lenni. Jól jöhet teszteléshez, vagy
pl. OSPF protokoll beállításához
#+BEGIN_SRC sh
interface loopback <szám>
ip address <ip cím> <subnet mask pontozott decimális formában>
[description <rövid leírás interfészről>]
no shutdown
#+END_SRC

** Duplexitás és sebesség beállítása
Global config mode-ban kell lenni. A switch általában automatikusan a
legjobbat választja
#+BEGIN_SRC sh
interface <interfésznév>
duplex <full|half|auto>
speed <10|100|1000|auto> #1000 Mb/s módot csak full-duplexben tudják
end
#+END_SRC

** Auto-MDIX
Global config mode-ban kell kiadni. A beállításával mindegy, hogy
milyen kábelt használunk (crossover vagy straight-through)
#+BEGIN_SRC sh
interface <interfész>
mdix auto
end
#+END_SRC
A sebességnek és a duplexitásnak is auto-nak kell lenniük

* Monitorozás és hibakeresés

** Bejegyzések verifikálása
Privileged EXEC mode-ban kell kiadni
#+BEGIN_SRC sh
show running_congig         # Éppen futó konfiguráció
show ip[v6] interface brief # Interfészek és a hozzájuk tartozó ip-címek
show ip[v6] route           # Routing tábla
show ip[v6] route static    # Routing tábla statikus bejegyzésekkel
show ipv6 route             # Routing tábla csak ipv6-os bejegyzésekkel
show interfaces [<intrf>]   # Interfészek
show arp                    # ARP tábla
show protocols              # Interfészek állapota
show version                # IOS verzió és egyebek
show cdp detail             # CDP protokoll által gyűjtött szomszédok
#+END_SRC
Lehet pipe-olni (|) is! A lehetséges programok:
- *section* <blokk>: kiírja az adott blokkot
- *include* <szöveg>: kiírja a szöveget tartalmazó sorokat
- *exclude* <szöveg>: kiírja a szöveggel nem tartalmazó sorokat
- *begin* <szöveg>: kiírja a szöveget tartalmazó sorral kezdve az
  összes sort

** Kapcsolatok verifikálása
Kiadható User EXEC mode-ban is
#+BEGIN_SRC sh
ping <ip(v6)-cím>
traceroute <ip-cím>
#+END_SRC

** Debug információk megjelenítése
Privileged EXEC mode-ban kell kiadni
#+BEGIN_SRC sh
debug <debugging funkciók, pl.: ip, dhcp, stb.>
undebug <debugging funkciók amiket le akarunk kapcsolni>
undebug <all>
#+END_SRC
A debug információk generálása és megjelenítése működésképtelenné
tehetik az eszközt!  

A debug információk alap esetben a =console= portra
kerülnek. Ennek kivédésére a ~debug~ parancs előtt ki kell adni a
~terminal monitor~ parancsot

* Biztonság

** Privileged EXEC mode-hoz jelszó beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
enable secret <jelszó>
#+END_SRC

** A konfigurációs fájlban lévő jelszavak titkosítása
Global config mode-ban kell lenni
#+BEGIN_SRC sh
service password-encryption
#+END_SRC

** Jelszavak minimális hosszának a beállítása 
Global config mode-ban kell lenni
#+BEGIN_SRC sh
security password min-length
#+END_SRC

** Brute-force támadások kivédése
Global config mode-ban kell lenni
#+BEGIN_SRC sh
login block_for <másodperc> attempts <próbálkozás> within <másodperc>
#+END_SRC

** Kapcsolat megszakítása egy adott idő elteltével
Console, VTY és AUX portokra lehet beállítani. Ennek megfelelő
mode-ban kell lenni
#+BEGIN_SRC sh
exec-timeout <perc>
#+END_SRC

** SSH
Először meg kell nézni, hogy az eszköz támogatja-e az ssh-t
#+BEGIN_SRC sh
show ip ssh
#+END_SRC
Ezután be kell állítani egy saját domain nevet
#+BEGIN_SRC sh
ip domain-name <domain-név>
#+END_SRC
Ezután SSH-kulcsot kell generálni.
Ha a ~modulus <...>~ részt nem fogadja el, akkor le kell hagyni
#+BEGIN_SRC sh
crypto key generate rsa general-keys modulus <360-2048>
#+END_SRC
Ezután el kell menteni egy felhasználót a helyi adatbázisban
#+BEGIN_SRC sh
username <felhasználónév> privilege 1 secret <jelszó>
#+END_SRC
Végül engedélyeznünk kell az SSH-kapcsolatot a VTY-ken

Global config mode-ban kell lenni
#+BEGIN_SRC sh
line vty 0 4
transport input ssh
login local
#+SRC_END

** Port biztonság
Global config mode-ban kell lenni
#+BEGIN_SRC sh
interface <interfész>
switchport mode access
switchport port-security [maximum <engedélyezett MAC-címek száma> | mac-address sticky]
#+END_SRC
Verifikálni a következő parancsokkal lehet
#+BEGIN_SRC sh
show port-security interface <interfész>
show port-security address   # Kiírja az összes biztonságos MAC-címet
#+END_SRC

* Routing

** Statikus útvonalak beállítása
Global config mode-ban kell kiadni
#+BEGIN_SRC sh
ip route <ip-cím> <pontozott decimális maszk> {next-hop-ip | exit-interface}
ip route 0.0.0.0 0.0.0.0 {next-hop-ip | exit-interface} #alapértelmezett útvonal esetén
ipv6 route ::/0 {next-hop-ipv6 | exit-interface} #alapértelmezett útvonal ipv6 esetén
#+END_SRC
Végére tehető az adminisztratív távolság, ha Floating Static Route-ot
konfigurálunk
