#+TITLE: Jegyzet a Cisco IOS oprendszerhez

* Általános IOS ismeretek

** Konfigurációs szintek

   - *User EXEC mode* (=>=): csak alapvető parancsok adhatóak ki,
     pl. státusz 

   - *Privileged EXEC mode* (=#=): User EXEC mode-ból az ~enable~
     paranccsal érhető el. Innen érhetőek el a konfigurációs módok,
     illetve itt lehet perzisztensé tenni a futó konfigurációt

   - *Global Configuration mode* (=(config)=): Privileged EXEC mode-ból
     a ~configure terminal~ paranccsal érhető el. Innen érhető el a
     többi alkonfigurációs szint, pl.: interface (=(config-if)=), line
     (=(config-li)=), router
     
   - Az alacsonyabb szintekre mindig az ~exit~ paranccsal lehet visszatérni

** Segítség

   - A =?= megadja az összes lehetséges parancs vagy argumentum
     értékét. Megkezdett parancsoknál és argumentumoknál is
     használható

   - A =<TAB>= gomb kiegészíti a parancsot vagy argumentumot a teljes
     nevére

   - Nem muszáj minden parancs vagy argumentum nevét teljesen kiírni,
     viszont a leírt rövidítéseknek egyértelműen kell azonosítaniuk a
     parancsot vagy az argumentumot

** Korábbi parancsok
   - fölfelé nyíl vagy C-p: előző parancs
   - lefelé nyíl vagy C-n: következő parancs
   - alapból a legutóbbi 10 parancs van eltárolva
   - ~show history~ paranccsal előhozhatóak Privileged EXEC mode-ban
   - ~terminal history size <szám>~ paranccsal bővíthető

* Globális konfiguráció

** Hosztnév beállítás
Global config mode-ban kell kiadni
#+BEGIN_SRC sh
hostname <hosztnév>
#+END_SRC

** Banner üzenet beállítása, ami megjelenik minden belépés előtt
Global config mode-ban kell kiadni 
#+BEGIN_SRC sh
banner motd <tetszőleges elválasztójel> <Üzenet, amiben figyelmeztetjük az
illetéktelen behatolókat, hogy törvénysértést követnek el>
<ugyanaz a tetszőleges elválasztójel>
#+END_SRC

** Default gateway beállítás
Global config mode-ban kell kiadni
#+BEGIN_SRC sh
ip default-gateway <ip-cím>
#+END_SRC

** Jelenleg futó konfiguráció elmentése
Privileged EXEC mode-ban kell kiadni.
#+BEGIN_SRC sh
copy running_config startup_config
#+END_SRC

** DNS lookup letiltása
Privileged EXEC mode-ban kell kiadni
#+BEGIN_SRC sh
no ip domain lookup
#+END_SRC

** BOOT környezeti változó beállítása
A BOOT környezeti változó beállításával adható meg a boot loader
számára, hogy hol keresse meg az IOS-t a flash tárolón
#+BEGIN_SRC sh
boot system flash:<IOS bináris>
#+END_SRC

* Interfészek konfigurálása

** Konzol jelszó beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
line console 0
password <jelszó>
login
#+END_SRC

** Virtuális terminál jelszó beállítás
Global config mode-ban kell lenni. A virtuális terminálok száma 0-tól
15-ig tart
#+BEGIN_SRC sh
line vty 0 15
passwod <jelszó>
login
#+END_SRC

** Interfész ip beállítás
Global config mode-ban kell lenni. A switchen =vlan 1=, a routeteren
=gigabithethernet= vagy =fastethernet= vagy valami ilyesmi a nevük
#+BEGIN_SRC sh
interface <interfésznév>
ip address <ip cím> <subnet mask pontozott decimális formában>
[description <rövid leírás interfészről>]
no shutdown
#+END_SRC

** Interfész ipv6 beállítás
Global config mode-ban kell lenni. A switchen =vlan 1=, a routeteren
=gigabithethernet= vagy =fastethernet= vagy valami ilyesmi a nevük
#+BEGIN_SRC sh
interface <interfésznév>
ipv6 address <global ipv6-cím>/<prefix-hossz decimálisan> [eui-64]
ipv6 address <link-local unicast ipv6-cím>/<prefix-hossz decimálisan> link-local
[description <rövid leírás interfészről>]
no shutdown
#+END_SRC
Ezek után ki kell adni =Global config mode=-ban az ~Ipv6
unicast-routing~ parancsot az unicast csomagok továbbításához

** Interfész loopback beállítás
Global config mode-ban kell lenni. Jól jöhet teszteléshez, vagy
pl. OSPF protokoll beállításához
#+BEGIN_SRC sh
interface loopback <szám>
ip address <ip cím> <subnet mask pontozott decimális formában>
[description <rövid leírás interfészről>]
no shutdown
#+END_SRC

** Duplexitás és sebesség beállítása
Global config mode-ban kell lenni. A switch általában automatikusan a
legjobbat választja
#+BEGIN_SRC sh
interface <interfésznév>
duplex <full|half|auto>
speed <10|100|1000|auto> #1000 Mb/s módot csak full-duplexben tudják
end
#+END_SRC

** Auto-MDIX
Global config mode-ban kell kiadni. A beállításával mindegy, hogy
milyen kábelt használunk (crossover vagy straight-through)
#+BEGIN_SRC sh
interface <interfész>
mdix auto
end
#+END_SRC
A sebességnek és a duplexitásnak is auto-nak kell lenniük

* Monitorozás és hibakeresés

** Bejegyzések verifikálása
Privileged EXEC mode-ban kell kiadni
#+BEGIN_SRC sh
show running_congig         # Éppen futó konfiguráció
show ip[v6] interface brief # Interfészek és a hozzájuk tartozó ip-címek
show ip[v6] route           # Routing tábla
show ip[v6] route static    # Routing tábla statikus bejegyzésekkel
show ipv6 route             # Routing tábla csak ipv6-os bejegyzésekkel
show interfaces [<intrf>]   # Interfészek
show arp                    # ARP tábla
show protocols              # Interfészek állapota
show version                # IOS verzió és egyebek
show cdp detail             # CDP protokoll által gyűjtött szomszédok
#+END_SRC
Lehet pipe-olni (|) is! A lehetséges programok:
- *section* <blokk>: kiírja az adott blokkot
- *include* <szöveg>: kiírja a szöveget tartalmazó sorokat
- *exclude* <szöveg>: kiírja a szöveggel nem tartalmazó sorokat
- *begin* <szöveg>: kiírja a szöveget tartalmazó sorral kezdve az
  összes sort

** Kapcsolatok verifikálása
Kiadható User EXEC mode-ban is
#+BEGIN_SRC sh
ping <ip(v6)-cím>
traceroute <ip-cím>
#+END_SRC

** Debug információk megjelenítése
Privileged EXEC mode-ban kell kiadni
#+BEGIN_SRC sh
debug <debugging funkciók, pl.: ip, dhcp, stb.>
undebug <debugging funkciók amiket le akarunk kapcsolni>
undebug <all>
#+END_SRC
A debug információk generálása és megjelenítése működésképtelenné
tehetik az eszközt!  

A debug információk alap esetben a =console= portra
kerülnek. Ennek kivédésére a ~debug~ parancs előtt ki kell adni a
~terminal monitor~ parancsot

* Biztonság

** Privileged EXEC mode-hoz jelszó beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
enable secret <jelszó>
#+END_SRC

** A konfigurációs fájlban lévő jelszavak titkosítása
Global config mode-ban kell lenni
#+BEGIN_SRC sh
service password-encryption
#+END_SRC

** Jelszavak minimális hosszának a beállítása 
Global config mode-ban kell lenni
#+BEGIN_SRC sh
security password min-length
#+END_SRC

** Brute-force támadások kivédése
Global config mode-ban kell lenni
#+BEGIN_SRC sh
login block_for <másodperc> attempts <próbálkozás> within <másodperc>
#+END_SRC

** Kapcsolat megszakítása egy adott idő elteltével
Console, VTY és AUX portokra lehet beállítani. Ennek megfelelő
mode-ban kell lenni
#+BEGIN_SRC sh
exec-timeout <perc>
#+END_SRC

** SSH
Először meg kell nézni, hogy az eszköz támogatja-e az ssh-t
#+BEGIN_SRC sh
show ip ssh
#+END_SRC
Ezután be kell állítani egy saját domain nevet
#+BEGIN_SRC sh
ip domain-name <domain-név>
#+END_SRC
Ezután SSH-kulcsot kell generálni.
Ha a ~modulus <...>~ részt nem fogadja el, akkor le kell hagyni
#+BEGIN_SRC sh
crypto key generate rsa general-keys modulus <360-2048>
#+END_SRC
Ezután el kell menteni egy felhasználót a helyi adatbázisban
#+BEGIN_SRC sh
username <felhasználónév> privilege 1 secret <jelszó>
#+END_SRC
Végül engedélyeznünk kell az SSH-kapcsolatot a VTY-ken

Global config mode-ban kell lenni
#+BEGIN_SRC sh
line vty 0 4
transport input ssh
login local
#+SRC_END

** Port biztonság
Global config mode-ban kell lenni
#+BEGIN_SRC sh
interface <interfész>
switchport mode access
switchport port-security [maximum <engedélyezett MAC-címek száma> | mac-address sticky]
#+END_SRC
Verifikálni a következő parancsokkal lehet
#+BEGIN_SRC sh
show port-security interface <interfész>
show port-security address   # Kiírja az összes biztonságos MAC-címet
#+END_SRC

* Routing

** Statikus útvonalak beállítása
Global config mode-ban kell kiadni
#+BEGIN_SRC sh
ip route <ip-cím> <pontozott decimális maszk> {next-hop-ip | exit-interface}
ip route 0.0.0.0 0.0.0.0 {next-hop-ip | exit-interface} #alapértelmezett útvonal esetén
ipv6 route ::/0 {next-hop-ipv6 | exit-interface} #alapértelmezett útvonal ipv6 esetén
#+END_SRC
Végére tehető az adminisztratív távolság, ha Floating Static Route-ot
konfigurálunk

* RIPv1

** RIP engedélyezése egy hálózaton
Global congig mode-ban kell lenni
#+BEGIN_SRC sh
routing rip
# router config mode-ba kerülünk
network <hálózat ip-cím>
#+END_SRC
Fogad RIP üzeneteket a hálózathoz tartozó interfészeken
és 30 másodpercenként küld update üzeneteket

** RIP verifikálása
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show ip protocols
show ip route | begin Gateway
#+END_SRC

** Verzió beállítása
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
router rip
version 2
#+END_SRC

** Summary Static Route letiltása
Global config mode-ban kell lenni
#+BEGIN_SRC sh
router rip
no auto-summary
end
#+END_SRC

** Passzív interfész beállítása 
Global config mode-ban kell lenni
#+BEGIN_SRC sh
router rip
passive-interface <interfész>
end
#+END_SRC
Letiltja az üzenetek küldését, viszont hirdeti az interfészhez 
tartozó hálózatot a többi interfészen

** Default static route beállítása
Global config mode-ban kell lenni
#+BEGIN_SRC sh
ip route 0.0.0.0 0.0.0.0 <next-hop-ip | exit-interfész>
router rip
default-information originate
end
#+END_SRC

* Tűzfalak
** ACL létrehozása, törlése és megjelenítése
 Global config mode-ban kell lenni
 #+BEGIN_SRC sh
 access-list <0-99 | 1300-1999> {deny | premit | remark} <forrás ip> [<forrás wildcard>] [log]
 no access-list <0-99 | 1300-1999>
 exit
 #+END_SRC
 Minden ACL hozzá van rendelve egy 0-99 vagy 1300-1999 közötti számhoz.

** ACL hozzáadása és eltávolítása interfészről
Global config mode-ban kell lenni
#+BEGIN_SRC sh
interface <interfésznév>
ip access-group {<ACL-szám | ACL-név>} {in | out}
no ip access-group
#+END_SRC

** ACL elnevezése
Global config mode-ban kell lenni
#+BEGIN_SRC sh
ip access-list {standard | extended} <név>
# itt standard named ACL mode-ba kerülünk
{permit | deny | remark} <forrás ip> [<forrás wildcard>] [log]
end
#+END_SRC

** ACL megváltoztatása
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show access-list <ACL-szám> # Itt kilistázza a szabályokat a szekvenciaszámmal együtt
conf t
ip access-list standard <ACL-szám>
no <szekvenciaszám>
end
#+END_SRC

** ACL verifikálása
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show access-lists
clear access-list counters # Lenulláza a bejegyzésekhez tartozó számlálót
#+END_SRC

** ACL VTY-n
Global config mode-ban kell lenni
#+BEGIN_SRC sh
line vty 0 4
login local
transport input ssh
access-class <ACL-szám> {in | out}
exit
access-list <ACL-szám> permit <forrás ip> <forrás wildcard>
access-list <ACL-szám> deny any
#+END_SRC

* DHCP
** DHCP beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
# IP-címek kihagyása
ip dhcp excluded-address <legkisebb IP-cím> <legnagyobb IP-cím>
ip dhcp pool <név>
# dhcp pool mode-ba kerülünk
network <hálózat ip> <hálózat maszk vagy \prefix>
default-router <gateway ip...>
dns-server <dns ip>
domain-name <név>
lease {<napok> [órák] [percek] | infinite}
netbios-name-server <ip>
#+END_SRC

** DHCP szervíz leállítása
Global config mode-ban kell lenni
#+BEGIN_SRC sh
no service dhcp
# újraengedélyezés
service dhcp
#+END_SRC

** DHCP verifikálás
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show running-config | section dhcp
show ip dhcp binding
show ip dhcp server statistics
#+END_SRC

** DHCP Relay Agent beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
interface <interfész>
ip helper-address <ip-cím>
end
#+END_SRC

** DHCP kliens beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
interface <interfész>
ip address dhcp
no shutdown
end
#+END_SRC

** Windows kliens beállítás
#+BEGIN_SRC sh
ipconfig /release
ipconfig /renew
#+END_SRC

* Vlan

** Vlan létrehozása/eltávolítása
Global config mode-ban kell lenni
#+BEGIN_SRC sh
[no] vlan <vlan szám>
# Vlan mode-ba kerülünk
name <név>
end
#+END_SRC

A törlésnél érdemes odafigyelni, hogy a vlan ne legyen hozzárendelve egy porthoz sem.

A vlan-ok a vlan.dat fájlban találhatóak, nem a running-configban. A `delete flash:vlan.dat`
paranccsal lehet kitörölni.

** Vlan hozzárendelése/eltávolítása egy portról
Global config mode-ban kell lenni
#+BEGIN_SRC sh
interface <interfész>
switchport mode access
switchport access vlan <vlan-id>
# Ha VoIP-et is akarunk: 
mls qos trust cos 
switchport voice vlan 150
end
#+END_SRC

Ha el lett rontva a vlan-id hozzárendelés, elég csak a ~switchport access vlan <vlan-id>~
parancsot kiadni a megfelelő interfészen.

Törlésnél a ~no switchport access vlan~ parancsot kell kiadni.

** Vlan verifikálás
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show vlan [name <név> | id <VID>]
show vlan brief
show vlan summary
show interfaces vlan <vlan-id>
show interface <interfész> switchport
#+END_SRC

** Trönkölt interfész beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
interface <interfész>
switchport mode trunk
switchport trunk native vlan <natív vlan-id>
swichport trunk allowed vlan <engedélyezett vlan-id lista>
# itt egyszerre kell megadni, nem lehet egyenként
end
#+END_SRC

** Trönkölt interfészek verifikálása
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show interface <interfész> switchport
show interface trunk
#+END_SRC

** DTP(Dynamic Trunking Protocol) beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
interface <interfész>
# Kikapcsolás
swithcport nonegotiate
# Visszakapcsolás (ez az alapértelmezett)
switchport mode dynamic auto
#+END_SRC

DTP switchport mode-ok:
  - ~access~: mindenképp access mode-ba lesz állítva
  - ~trunk~: mindenképpen trunking mode-ba lesz állítva
  - ~dynamic auto~:
    - trunk mode-ban lesz, ha a szomszédja ~dynamic desirable~ vagy ~trunk~
    - access mode-ban lesz, ha a szomszédja ~dynamic auto~ vagy ~access~
    - ez az alapértelmezett
  - ~dynamic desirable~:
    - trunk mode-ban lesz, ha a szomszédja ~dynamic desirable~, ~dynamic auto~ vagy ~trunk~
    - access mode-ban lesz, ha a szomszédja ~access~

** DTP verifikáció
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show dtp interface <interfész>
#+END_SRC

** Router-on-a-Stick inter-vlan routing
Global config mode-ban kell lenni
#+BEGIN_SRC sh
interface <interfész>.<vlan-id>
# Alinterfész mode-ba kerülünk
encapsulation dot1q <vlan-id>
ip address <ip-cím> <maszk>
# Ugyanez a többi alinterfészre
...
interface <interfész>
no shutdown
#+END_SRC

** Layer 3 switch inter-vlan routing
Fel kell konfigurálni a switch megfelelő portjait a megfelelő vlan-okkal, majd a
vlan interfészekre (SVI - Switch Virtual Interface) kell megadni a default-gateway-t.
Ezután engedélyezni kell az ~ip routing~-ot.

Ha egy másik layer 3-as ezközzel kötjük össze a switch-et, akkor az eszköz felé
menő porton ~no switchport~ parancsot kell kiadni.

* DHCPv6
** Stateless server beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
ipv6 unicast-routing
ipv6 dhcp pool <név>
# dhcp pool mode-ba kerülünk
dns-server <dns ip>
domain-name <név>
exit
interface <név>
ipv6 dhcp server <pool név>
ipv6 nd other-config-flag
#+END_SRC

** Stateless DHCPv6 kliens beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
ipv6 unicast-routing
interface <név>
ipv6 enable
ipv6 address autoconfig
end
#+END_SRC

** Stateful server beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
ipv6 unicast-routing
ipv6 dhcp pool <név>
# dhcp pool mode-ba kerülünk
address prefix <prefix\hossz>
dns-server <dns ip>
domain-name <név>
exit
interface <név>
ipv6 dhcp server <pool név>
ipv6 nd managed-config-flag
ipv6 nd prefix default no-autoconfig
#+END_SRC

** Stateful kliens beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
interface <név>
ipv6 enable
ipv6 address dhcp
#+END_SRC

** Verifikáció
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show ipv6 dhcp pool
show ipv6 dhcp binding
show ipv6 dhcp interface
#+END_SRC

** Relay Agent beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
interface <név>
ipv6 dhcp relay destination <ipv6-cím>
end
#+END_SRC

* NAT

** Statikus NAT
Global config mode-ban kell lenni
#+BEGIN_SRC sh
ip nat inside source static <local ip> <global ip> # 'no' kulcsszóval lehet letiltani
# Belső vagy külső interfész megadása
interface <interfész>
ip nat [inside | outside]
exit
#+END_SRC

** Dinamikus NAT
Global config mode-ban kell lenni
#+BEGIN_SRC sh
# Pool megadása
ip nat pool <pool név> <első ip> <utolsó ip> {netmask <maszk> | prefix-length <prefix>}
# ACL megadása, ami csak a fordítandó címeket tartalmazza
access-list <ACL szám> permit <forrás ip> [<wildcard>]
# ACL hozzákötése egy pool-hoz
ip nat inside source list <ACL szám> pool <pool név>
interface <interfész>
ip nat [inside | outside]
#+END_SRC
Minden dinamikus bejegyzés 24 óra után törlődik. Felülírni
a global config mode-ban az alábbi paranccsal lehet.
#+BEGIN_SRC sh
ip nat translation timeout <másodpercek>
#+END_SRC
Törölni pedig ezzel.
#+BEGIN_SRC sh
clear ip nat translation * # Mindent töröl
clear ip nat translations inside <globális ip> <lokális ip> [outside <lokális ip> <globális ip>]
#+END_SRC

** PAT
Global config mode-ban kell lenni
#+BEGIN_SRC sh
ip nat pool <pool név> <első ip> <utolsó ip> {netmask <maszk> | prefix-length <prefix>}
# ACL megadása, ami csak a fordítandó címeket tartalmazza
access-list <ACL szám> premit <forrás ip> [<wildcard>]
# ACL hozzákötése egy pool-hoz
ip nat inside source list <ACL szám> pool <pool név> overload
# ACL hozzákötése egy ip-címhez
ip nat inside source list <ACL szám> interface <külső interfész> overload
interface <interfész>
ip nat [inside | outside]
#+END_SRC
Ugyanaz, mint a dinamikus NAT-nál, csak itt szerepel az
overload kulcsszó a NAT létrehozásánál

** Port forwarding
Global config mode-ban kell lenni
#+BEGIN_SRC sh
ip nat inside source static {tcp | udp} <lokális ip> <lokális port> <globális ip> <globális port> [extendable]
#+END_SRC
Az extendable kulcsszóval több portot is be lehet állítani

** Verifikálás
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show ip nat translations [verbose]
show ip nat statistics
# Törlés
clear ip nat statistics
#+END_SRC

** NATolt csomagok megjelenítése
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
debug ip nat [detailed]
#+END_SRC

* CDP

** Engedélyezés és tiltás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
# Globálisan
[no] cdp run
# Egy interfészre
interface <interfész>
[no] cdp enable
exit
#+END_SRC

** Információ
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show cdp
show cdp neighbors [detail]
show cdp interface    # Mely interfészeken van engedélyezve
#+END_SRC

* LLDP

** Engedélyezés/tiltás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
# Globális
[no] lldp run
# Lokális
interface <interfész>
[no] lldp transmit
[no] lldp receive
#+END_SRC

** Információ
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show cdp neighbors [detail]
#+END_SRC
Capacity oszlopban a B Bridge, ami switchet jelent

* NTP

** Manuális beállítás
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
clock set <óra:perc:másodperc> <hónap nap év>
#+END_SRC

** NTP szerver beállítás
Global config mode-ban kell lenni
#+BEGIN_SRC sh
ntp server <ip-cím>
end
#+END_SRC

** Verifikálás
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show clock detail
show ntp associations
show ntp status
#+END_SRC

* Logging (Syslog)

** Engedélyezés
Global config mode-ban kell kiadni
#+BEGIN_SRC sh
logging <syslog szerver cím>
logging trap <level> # level vagy az annál alacsonyabb szintű üzenetek lesznek elküldve a syslog szervernek
logging source-interface <interfész> # Ennek az interfésznek az ip-címe kerül a syslog üzenetbe függetlenül attól, hogy melyik interfészen ment ki
#+END_SRC

** Verifikálás
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show logging
#+END_SRC
Ez is pipeolható, ld. [[*Bejegyz%C3%A9sek verifik%C3%A1l%C3%A1sa][Bejegyzések verifikálása]]

* Fájlrendszerek

** Fájlrendszerek megjelenítése
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
show file systems
dir                 # Olyan, mint linuxon az ls
cd <könyvtár vagy fájlrendszer>
#+END_SRC
A tftp, flash és nvram fájlrendszerek az érdekesek

** Konfiguráció elmentése/visszaállítása tftp-vel
Privileged EXEC mode-ban kell lenni
#+BEGIN_SRC sh
copy running-config tftp
# Itt kérdezni fogja a szerver címét és a fájl nevét
copy tftp running-config
# Cím + fájlnév megadása
#+END_SRC
Ugyanez elvégezhető USB-s eszközzel. Ugyanez elvégezhető az IOS operációs rendszerrel is

** Jelszó visszaállítás
Konzolon keresztül a bootolás közben egy break szekvenciát kell beiktatni (putty-ban Ctrl-Break)
így kerülhetünk ROMMON mode-ba
#+BEGIN_SRC sh
confreg 0x2142 # Bootolásnál nem veszi figyelembe a startup-configot
reset          # Rebootol
#+END_SRC
A rebootolás után Privileged EXEC mode-ban
#+BEGIN_SRC sh
copy startup-config running-config
conf t
# Jelszavak beállítása újra
config-register 0x2102
end
copy running-config startup-config
reload
#+END_SRC

** Új rendszerkép betöltése
Global config mode-ban kell kiadni
#+BEGIN_SRC sh
boot system <fájlrendszer>://<bináris állomány>
exit
copy runnning-config startup-config
reload
#+END_SRC

* EtherChannel

** LACP beállítás
Global config módban kell kiadni.
#+BEGIN_SRC sh
interface range <interfésznév-interfésznév>
channel-group <etherchannel sorszáma> mode [active|passive|on]
exit
#+END_SRC

Ezután a channel group sorszámát is lehet használni kiválasztáshoz:
~interface port-channel <etherchannel sorszáma>~

** LACP verifikálás
Privileged EXEC módban kell kiadni.
#+BEGIN_SRC sh
show interfaces port-channel <etherchannel sorszám>
show etherchannel summary
show etherchannel port-channel
show interfaces <interfésznév> etherchannel
#+END_SRC